const MASTER_KEY = 'master_data_v1';
const NV_KEY = 'nhanviens_v1';

// 🔸 Dữ liệu danh mục
const defaultMaster = {
  phongBan: [
    "Ban Giám đốc", "Nhân sự", "Kế toán", "Kinh doanh",
    "Marketing", "Kỹ thuật", "Phát triển phần mềm",
    "Hỗ trợ khách hàng", "IT hạ tầng"
  ],
  chucVu: ["Nhân viên", "Trưởng nhóm", "Trưởng phòng"],
  trinhDo: ["Trung cấp", "Cao đẳng", "Đại học"],
  chuyenMon: ["CNTT", "Kế toán", "Quản trị"],
  bangCap: ["Cử nhân", "Kỹ sư", "Thạc sĩ"]
};

// 🔸 Dữ liệu nhân viên mẫu (chuyển từ file cũ sang đây)
const SAMPLE_EMPLOYEES = [
  {
    "maNV": "NV001",
    "hoTen": "Lee min ho",
    "gioiTinh": "Nam",
    "ngaySinh": "1987-06-22",
    "trangThai": "Đang làm việc",
    "phongBan": "Marketing",
    "chucVu": "Trưởng phòng",
    "trinhDo": "Thạc sĩ",
    "chuyenMon": "Quản trị kinh doanh",
    "bangCap": "Bằng 1",
    "cccd": "011223344",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Quản lý"
  },
  {
    "maNV": "NV002",
    "hoTen": "Phạm Văn Trường Vũ",
    "gioiTinh": "Nam",
    "ngaySinh": "1990-05-15",
    "trangThai": "Đang làm việc",
    "phongBan": "Kế toán",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Kế toán - Kiểm toán",
    "bangCap": "Bằng 1",
    "cccd": "022334455",
    "hoKhau": "TP. HCM",
    "avatar": "",
    "nhom": "Kế toán tổng hợp"
  },
  {
    "maNV": "NV003",
    "hoTen": "Nguyễn Kim Ngọc",
    "gioiTinh": "Nữ",
    "ngaySinh": "1988-11-30",
    "trangThai": "Đang làm việc",
    "phongBan": "Nhân sự",
    "chucVu": "Trưởng phòng",
    "trinhDo": "Đại học",
    "chuyenMon": "Quản trị nhân lực",
    "bangCap": "Bằng 1",
    "cccd": "033445566",
    "hoKhau": "Đà Nẵng",
    "avatar": "",
    "nhom": "Quản lý"
  },
  {
    "maNV": "NV004",
    "hoTen": "Nguyễn Văn Quyết",
    "gioiTinh": "Nam",
    "ngaySinh": "1985-01-20",
    "trangThai": "Đang làm việc",
    "phongBan": "IT",
    "chucVu": "Trưởng phòng",
    "trinhDo": "Kỹ sư",
    "chuyenMon": "Công nghệ thông tin",
    "bangCap": "Bằng 1",
    "cccd": "044556677",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Quản lý"
  },
  {
    "maNV": "NV005",
    "hoTen": "Nguyễn Chí Đạo",
    "gioiTinh": "Nam",
    "ngaySinh": "1986-09-10",
    "trangThai": "Đang làm việc",
    "phongBan": "Kinh doanh",
    "chucVu": "Trưởng phòng",
    "trinhDo": "Đại học",
    "chuyenMon": "Quản trị kinh doanh",
    "bangCap": "Bằng 1",
    "cccd": "055667788",
    "hoKhau": "Hải Phòng",
    "avatar": "",
    "nhom": "Quản lý"
  },
  {
    "maNV": "NV006",
    "hoTen": "Lê Thị Hoa",
    "gioiTinh": "Nữ",
    "ngaySinh": "1995-03-12",
    "trangThai": "Đang làm việc",
    "phongBan": "Marketing",
    "chucVu": "Nhân viên",
    "trinhDo": "Cao đẳng",
    "chuyenMon": "Marketing",
    "bangCap": "Bằng 2",
    "cccd": "066778899",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Content"
  },
  {
    "maNV": "NV007",
    "hoTen": "Hoàng Văn An",
    "gioiTinh": "Nam",
    "ngaySinh": "1993-07-25",
    "trangThai": "Đang làm việc",
    "phongBan": "Marketing",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Truyền thông đa phương tiện",
    "bangCap": "Bằng 1",
    "cccd": "077889900",
    "hoKhau": "Bắc Ninh",
    "avatar": "",
    "nhom": "Digital"
  },
  {
    "maNV": "NV008",
    "hoTen": "Vũ Minh Anh",
    "gioiTinh": "Nữ",
    "ngaySinh": "1996-02-18",
    "trangThai": "Đang làm việc",
    "phongBan": "Marketing",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Báo chí",
    "bangCap": "Bằng 1",
    "cccd": "088990011",
    "hoKhau": "TP. HCM",
    "avatar": "",
    "nhom": "Content"
  },
  {
    "maNV": "NV009",
    "hoTen": "Đặng Thị Lan",
    "gioiTinh": "Nữ",
    "ngaySinh": "1991-12-05",
    "trangThai": "Đang làm việc",
    "phongBan": "Kế toán",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Kế toán",
    "bangCap": "Bằng 1",
    "cccd": "099001122",
    "hoKhau": "Hà Nam",
    "avatar": "",
    "nhom": "Kế toán thuế"
  },
  {
    "maNV": "NV010",
    "hoTen": "Ngô Văn Hùng",
    "gioiTinh": "Nam",
    "ngaySinh": "1992-04-08",
    "trangThai": "Đang làm việc",
    "phongBan": "Kế toán",
    "chucVu": "Nhân viên",
    "trinhDo": "Cao đẳng",
    "chuyenMon": "Tài chính ngân hàng",
    "bangCap": "Bằng 2",
    "cccd": "011223300",
    "hoKhau": "Thái Bình",
    "avatar": "",
    "nhom": "Kế toán tổng hợp"
  },
  {
    "maNV": "NV011",
    "hoTen": "Trần Văn Nam",
    "gioiTinh": "Nam",
    "ngaySinh": "1994-08-14",
    "trangThai": "Đang làm việc",
    "phongBan": "Nhân sự",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Quản trị nhân lực",
    "bangCap": "Bằng 1",
    "cccd": "022334411",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Tuyển dụng"
  },
  {
    "maNV": "NV012",
    "hoTen": "Lý Thị Bích",
    "gioiTinh": "Nữ",
    "ngaySinh": "1990-10-21",
    "trangThai": "Đang làm việc",
    "phongBan": "Nhân sự",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Luật",
    "bangCap": "Bằng 1",
    "cccd": "033445522",
    "hoKhau": "Quảng Ninh",
    "avatar": "",
    "nhom": "Chế độ & Chính sách"
  },
  {
    "maNV": "NV013",
    "hoTen": "Phạm Văn Long",
    "gioiTinh": "Nam",
    "ngaySinh": "1992-03-03",
    "trangThai": "Đang làm việc",
    "phongBan": "IT",
    "chucVu": "Nhân viên",
    "trinhDo": "Kỹ sư",
    "chuyenMon": "Công nghệ thông tin",
    "bangCap": "Bằng 1",
    "cccd": "044556633",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Development"
  },
  {
    "maNV": "NV014",
    "hoTen": "Hà Thị Thu",
    "gioiTinh": "Nữ",
    "ngaySinh": "1997-06-19",
    "trangThai": "Đang làm việc",
    "phongBan": "IT",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Hệ thống thông tin",
    "bangCap": "Bằng 1",
    "cccd": "055667744",
    "hoKhau": "Phú Thọ",
    "avatar": "",
    "nhom": "Development"
  },
  {
    "maNV": "NV015",
    "hoTen": "Bùi Văn Tuấn",
    "gioiTinh": "Nam",
    "ngaySinh": "1991-11-07",
    "trangThai": "Đang làm việc",
    "phongBan": "IT",
    "chucVu": "Nhân viên",
    "trinhDo": "Cao đẳng",
    "chuyenMon": "Quản trị mạng",
    "bangCap": "Bằng 2",
    "cccd": "066778855",
    "hoKhau": "Hưng Yên",
    "avatar": "",
    "nhom": "System Admin"
  },
  {
    "maNV": "NV016",
    "hoTen": "Đỗ Thị Mai",
    "gioiTinh": "Nữ",
    "ngaySinh": "1998-04-23",
    "trangThai": "Đang làm việc",
    "phongBan": "Kinh doanh",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Kinh tế đối ngoại",
    "bangCap": "Bằng 1",
    "cccd": "077889966",
    "hoKhau": "TP. HCM",
    "avatar": "",
    "nhom": "Sales Team 1"
  },
  {
    "maNV": "NV017",
    "hoTen": "Hoàng Văn Hải",
    "gioiTinh": "Nam",
    "ngaySinh": "1993-09-11",
    "trangThai": "Đang làm việc",
    "phongBan": "Kinh doanh",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Quản trị kinh doanh",
    "bangCap": "Bằng 1",
    "cccd": "088990077",
    "hoKhau": "Thanh Hóa",
    "avatar": "",
    "nhom": "Sales Team 2"
  },
  {
    "maNV": "NV018",
    "hoTen": "Nguyễn Thị Linh",
    "gioiTinh": "Nữ",
    "ngaySinh": "1996-01-27",
    "trangThai": "Đang làm việc",
    "phongBan": "Kinh doanh",
    "chucVu": "Nhân viên",
    "trinhDo": "Cao đẳng",
    "chuyenMon": "Marketing",
    "bangCap": "Bằng 2",
    "cccd": "099001188",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Sales Team 1"
  },
  {
    "maNV": "NV019",
    "hoTen": "Lê Văn Dũng",
    "gioiTinh": "Nam",
    "ngaySinh": "1995-05-02",
    "trangThai": "Đang làm việc",
    "phongBan": "Marketing",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Marketing",
    "bangCap": "Bằng 1",
    "cccd": "011223399",
    "hoKhau": "Đà Nẵng",
    "avatar": "",
    "nhom": "Digital"
  },
  {
    "maNV": "NV020",
    "hoTen": "Trần Thị Kim",
    "gioiTinh": "Nữ",
    "ngaySinh": "1994-07-16",
    "trangThai": "Nghỉ thai sản",
    "phongBan": "Marketing",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Ngôn ngữ Anh",
    "bangCap": "Bằng 1",
    "cccd": "022334400",
    "hoKhau": "TP. HCM",
    "avatar": "",
    "nhom": "Content"
  },
  {
    "maNV": "NV021",
    "hoTen": "Phan Văn Giang",
    "gioiTinh": "Nam",
    "ngaySinh": "1989-12-11",
    "trangThai": "Đang làm việc",
    "phongBan": "Kế toán",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Kế toán",
    "bangCap": "Bằng 1",
    "cccd": "033445511",
    "hoKhau": "Nghệ An",
    "avatar": "",
    "nhom": "Kế toán thuế"
  },
  {
    "maNV": "NV022",
    "hoTen": "Vũ Thị Thủy",
    "gioiTinh": "Nữ",
    "ngaySinh": "1984-02-28",
    "trangThai": "Đang làm việc",
    "phongBan": "Kế toán",
    "chucVu": "Kế toán trưởng",
    "trinhDo": "Thạc sĩ",
    "chuyenMon": "Kế toán - Kiểm toán",
    "bangCap": "Bằng 1",
    "cccd": "044556622",
    "hoKhau": "Hải Dương",
    "avatar": "",
    "nhom": "Quản lý"
  },
  {
    "maNV": "NV023",
    "hoTen": "Đinh Văn Mạnh",
    "gioiTinh": "Nam",
    "ngaySinh": "1991-06-07",
    "trangThai": "Đang làm việc",
    "phongBan": "Nhân sự",
    "chucVu": "Chuyên viên tuyển dụng",
    "trinhDo": "Đại học",
    "chuyenMon": "Quản trị nhân lực",
    "bangCap": "Bằng 1",
    "cccd": "055667733",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Tuyển dụng"
  },
  {
    "maNV": "NV024",
    "hoTen": "Hoàng Thị Nguyệt",
    "gioiTinh": "Nữ",
    "ngaySinh": "1993-10-17",
    "trangThai": "Đang làm việc",
    "phongBan": "Nhân sự",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Luật",
    "bangCap": "Bằng 1",
    "cccd": "066778844",
    "hoKhau": "Bắc Giang",
    "avatar": "",
    "nhom": "Chế độ & Chính sách"
  },
  {
    "maNV": "NV025",
    "hoTen": "Lâm Văn Bình",
    "gioiTinh": "Nam",
    "ngaySinh": "1996-01-01",
    "trangThai": "Đang làm việc",
    "phongBan": "IT",
    "chucVu": "Lập trình viên",
    "trinhDo": "Kỹ sư",
    "chuyenMon": "Phần mềm",
    "bangCap": "Bằng 1",
    "cccd": "077889955",
    "hoKhau": "Lạng Sơn",
    "avatar": "",
    "nhom": "Development"
  },
  {
    "maNV": "NV026",
    "hoTen": "Ngô Thị Thanh",
    "gioiTinh": "Nữ",
    "ngaySinh": "1998-03-14",
    "trangThai": "Đang làm việc",
    "phongBan": "IT",
    "chucVu": "Tester",
    "trinhDo": "Đại học",
    "chuyenMon": "Công nghệ thông tin",
    "bangCap": "Bằng 1",
    "cccd": "088990066",
    "hoKhau": "Vĩnh Phúc",
    "avatar": "",
    "nhom": "Development"
  },
  {
    "maNV": "NV027",
    "hoTen": "Dương Văn Tùng",
    "gioiTinh": "Nam",
    "ngaySinh": "1990-08-20",
    "trangThai": "Đang làm việc",
    "phongBan": "Kinh doanh",
    "chucVu": "Nhân viên",
    "trinhDo": "Cao đẳng",
    "chuyenMon": "Thương mại",
    "bangCap": "Bằng 2",
    "cccd": "099001177",
    "hoKhau": "TP. HCM",
    "avatar": "",
    "nhom": "Sales Team 2"
  },
  {
    "maNV": "NV028",
    "hoTen": "Mai Thị Ánh",
    "gioiTinh": "Nữ",
    "ngaySinh": "1997-12-01",
    "trangThai": "Đang làm việc",
    "phongBan": "Kinh doanh",
    "chucVu": "Nhân viên",
    "trinhDo": "Đại học",
    "chuyenMon": "Kinh tế",
    "bangCap": "Bằng 1",
    "cccd": "011223388",
    "hoKhau": "Cần Thơ",
    "avatar": "",
    "nhom": "Sales Team 1"
  },
  {
    "maNV": "NV029",
    "hoTen": "Phùng Văn Khoa",
    "gioiTinh": "Nam",
    "ngaySinh": "1994-04-13",
    "trangThai": "Đang làm việc",
    "phongBan": "Marketing",
    "chucVu": "Digital Marketer",
    "trinhDo": "Đại học",
    "chuyenMon": "Marketing",
    "bangCap": "Bằng 1",
    "cccd": "022334499",
    "hoKhau": "Hà Tây",
    "avatar": "",
    "nhom": "Digital"
  },
  {
    "maNV": "NV030",
    "hoTen": "Tạ Thị Diệp",
    "gioiTinh": "Nữ",
    "ngaySinh": "1995-10-26",
    "trangThai": "Đang làm việc",
    "phongBan": "Marketing",
    "chucVu": "Content Creator",
    "trinhDo": "Đại học",
    "chuyenMon": "Báo chí và Truyền thông",
    "bangCap": "Bằng 1",
    "cccd": "033445500",
    "hoKhau": "Hà Nội",
    "avatar": "",
    "nhom": "Content"
  }
];

// 🔸 Xử lý lưu danh mục
const Data = {
  _load() {
    try {
      const raw = localStorage.getItem(MASTER_KEY);
      if (!raw) {
        localStorage.setItem(MASTER_KEY, JSON.stringify(defaultMaster));
        return JSON.parse(JSON.stringify(defaultMaster));
      }
      return JSON.parse(raw);
    } catch {
      return JSON.parse(JSON.stringify(defaultMaster));
    }
  },
  getAll() { return this._load(); },
  saveAll(obj) { localStorage.setItem(MASTER_KEY, JSON.stringify(obj)); },
  addTo(key, value) {
    if (!value) return;
    const m = this._load();
    if (!m[key]) m[key] = [];
    if (!m[key].includes(value)) m[key].push(value);
    this.saveAll(m);
  }
};

// 🔸 Nếu chưa có nhân viên thì khởi tạo mẫu
if (!localStorage.getItem(NV_KEY)) {
  localStorage.setItem(NV_KEY, JSON.stringify(SAMPLE_EMPLOYEES));
  console.log("Đã khởi tạo 30 nhân viên mẫu");
}
